version: "3.8"

services:
  noc1:
    image: noc1:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noc1
    restart: unless-stopped
    ports:
      - "${NOC1_PORT:-9969}:8081"
    environment:
      - PORT=8081
      - REFRESH_MINUTES=15
      - ADGUARD2_PASSWORD=${ADGUARD2_PASSWORD}
      - ADGUARD2_URL=${ADGUARD2_URL}
      - ADGUARD2_USERNAME=${ADGUARD2_USERNAME}
      - ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
      - ADGUARD_URL=${ADGUARD_URL}
      - ADGUARD_USERNAME=${ADGUARD_USERNAME}
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - CROWDSEC_API_URL=${CROWDSEC_API_URL}
      - CROWDSEC_MACHINE_PASS=${CROWDSEC_MACHINE_PASS}
      - CROWDSEC_MACHINE_USER=${CROWDSEC_MACHINE_USER}
      - HASS_TOKEN=${HASS_TOKEN}
      - HASS_URL=${HASS_URL}
      - LC_API_KEY=${LC_API_KEY}
      - LC_OID=${LC_OID}
      - LIMACHARLIE_API_KEY=${LIMACHARLIE_API_KEY}
      - LIMACHARLIE_OID=${LIMACHARLIE_OID}
      - NPM_EMAIL=${NPM_EMAIL}
      - NPM_PASSWORD=${NPM_PASSWORD}
      - NPM_URL=${NPM_URL}
      - OVERSEERR_API_KEY=${OVERSEERR_API_KEY}
      - OVERSEERR_URL=${OVERSEERR_URL}
      - PBS_PASSWORD=${PBS_PASSWORD}
      - PBS_URL=${PBS_URL}
      - PBS_USERNAME=${PBS_USERNAME}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - PLEX_URL=${PLEX_URL}
      - PORTAINER_PASSWORD=${PORTAINER_PASSWORD}
      - PORTAINER_URL=${PORTAINER_URL}
      - PORTAINER_USERNAME=${PORTAINER_USERNAME}
      - PROWLARR_API_KEY=${PROWLARR_API_KEY}
      - PROWLARR_URL=${PROWLARR_URL}
      - PROXMOX_HOST=${PROXMOX_HOST}
      - PROXMOX_TOKEN_ID=${PROXMOX_TOKEN_ID}
      - PROXMOX_TOKEN_SECRET=${PROXMOX_TOKEN_SECRET}
      - QNAP1_HOST=${QNAP1_HOST}
      - QNAP2_HOST=${QNAP2_HOST}
      - QNAP3_HOST=${QNAP3_HOST}
      - QNAP_PASSWORD=${QNAP_PASSWORD}
      - QNAP_USERNAME=${QNAP_USERNAME}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - RADARR_URL=${RADARR_URL}
      - SABNZBD_API_KEY=${SABNZBD_API_KEY}
      - SABNZBD_URL=${SABNZBD_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - SONARR_URL=${SONARR_URL}
      - TAILSCALE_API_KEY=${TAILSCALE_API_KEY}
      - TAUTULLI_API_KEY=${TAUTULLI_API_KEY}
      - TAUTULLI_URL=${TAUTULLI_URL}
      - UNIFI_PASSWORD=${UNIFI_PASSWORD}
      - UNIFI_URL=${UNIFI_URL}
      - UNIFI_USERNAME=${UNIFI_USERNAME}
      - UPTIME_KUMA_API_KEY=${UPTIME_KUMA_API_KEY}
      - UPTIME_KUMA_URL=${UPTIME_KUMA_URL}
      - URBACKUP_PASSWORD=${URBACKUP_PASSWORD}
      - URBACKUP_URL=${URBACKUP_URL}
      - URBACKUP_USERNAME=${URBACKUP_USERNAME}
      - WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD}
      - WAZUH_API_USER=${WAZUH_API_USER}
      - WAZUH_INDEXER_HOST=${WAZUH_INDEXER_HOST}
      - WAZUH_INDEXER_PASS=${WAZUH_INDEXER_PASS}
      - WAZUH_INDEXER_USER=${WAZUH_INDEXER_USER}
      - WG_PASSWORD=${WG_PASSWORD}
      - WG_URL=${WG_URL}
      - WG_USERNAME=${WG_USERNAME}
